### ISSUE TITLE
Array path->pts is out of bounds

### ISSUE THREAD

**Issue by SergeySlice** [memononen/nanosvg#127]
path->pts is an array of float reallocated at nanosvg.h:line 694 in nsvg__addPoint
path->cpts is a number of allocated pairs, can be 0,8,16,32... Propose path->cpts=8.
path->npts is a number of used pairs, increasing 0,1,2... Propose path->npts=7 
Condition 'if (p->npts+1 > p->cpts)' { will be false and no new realloc. There is 16 floats allocated.
p->npts++ will be 8.
Then look into nanosvgrast.h:line 375,
`	for (i = 0; i < path->npts-1; i += 3) {
			float* p = &path->pts[i*2];
			nsvg__flattenCubicBez(r, p[0]*scale,p[1]*scale, p[2]*scale,p[3]*scale, p[4]*scale,p[5]*scale, p[6]*scale,p[7]*scale, 0, 0);
		}
`
Last i==6 will be addressed to [6*2+7] which is out of bound.
What I missed?

**Comment by memononen** [comment]
The path always consists of cubic bezier segments.

For example moveto A + lineto B + lineto C will create 7 points (lines
expand to curves too):
[A, B0, B1, B, C0, C1, C],

which translates to cubic curves: (A,B0,B1,B) (B,B0,B1,C).

You access 4 consecutive points to render a curve and advance by 3 since
the curves create continuous path.

As per you example, when i == 6: 6 < (7-1) is false.

**Comment by SergeySlice** [comment]
6 < (8-1) true
because of p->npts++ before this.

**Comment by memononen** [comment]
8 is not a valid number of points in the path. You have 1 + #segments * 3
points.

**Comment by SergeySlice** [comment]
d="M313 258q-42 -2 -71.5 -1.5t-56.5 1.5t-56.5 1t-71.5 -1q-23 -1 -34.5 8.5t-12 21.5t10.5 22t34 11q42 1 71.5 0.5t57 -1.5t57 -1.5t71.5 0.5q28 1 41 -8t12.5 -20.5t-14 -21.5t-38.5 -11z"

I am trying to implement SVG fonts and they consist of not only cubic beziers. Parsing it causes memory crash so I found this problem.
OK, as only cubic bezier supported then this is not the issue for current codes.

**Comment by memononen** [comment]
Everything is converted to cubic beziers. Take a look at `nsvg__parsePath()`. It parses path strings and calls specific functions to convert the commands to cubic beziers.

**Comment by SergeySlice** [comment]
Is it only my problem?
[LetterO.svg.zip](https://github.com/memononen/nanosvg/files/2204453/LetterO.svg.zip)
This simple shape is not rendered correctly.

**Comment by SergeySlice** [comment]
This shape consists of two closed path. May be parsing second path we have to reset p->pts?
~~~

static void nsvg__resetPath(NSVGparser* p)
{
	p->npts = 0;
+      p->cpts = 0;
}

~~~

**Comment by SergeySlice** [comment]
Even may be
~~~
free(p->pts);
~~~

**Comment by memononen** [comment]
Nope. `cpts` tells how many points are allocated. Can you show what is the wrong result you're getting? I'm not currently at my work computer and cannot test your case.

**Comment by SergeySlice** [comment]
![2018-07-19 6 31 39](https://user-images.githubusercontent.com/485515/42920048-92945f00-8b1d-11e8-96e1-ba1c6050a653.png)

**Comment by memononen** [comment]
![svg](https://user-images.githubusercontent.com/5249992/42922526-95a87454-8b29-11e8-9c3a-1d42665e27c4.png)

Works fine in the example2 with latest code.

**Comment by SergeySlice** [comment]
My problem is reproducible. I still can't catch the origin of it.
Workaround is
~~~
if (p->npts*2+1 > p->cpts)
~~~
I know it is wrong but it shows that the problem somewhere in memory allocaton. May be because of my malloc/realloc have a bug.
I see no other difference with your current codes.

**Comment by memononen** [comment]
Unfortunately I'm not able to help unless I can reproduce the problem on my
end.

**Comment by SergeySlice** [comment]
Yes, it is my mistake. Sorry for disturbance and thank you for explanations.
