### ISSUE TITLE
Division by float 0

### ISSUE THREAD

**Issue by qarmin** [memononen/nanosvg#179]
```
thirdparty/nanosvg/nanosvg.h:2161:49: runtime error: division by zero
```
https://github.com/memononen/nanosvg/blob/25241c5a8f8451d41ab1b02ab2d865b01600d949/src/nanosvg.h#L2161

not sure about reproduction steps

**Comment by SergeySlice** [comment]
I resolved this in such a way
~~~~
  if ((hda < 1e-3f) && (hda > -1e-3f)) hda *= 0.5f;
  else hda = (1.0f - cosf(hda)) / sinf(hda);
  kappa = fabsf(4.0f / 3.0f * hda);
~~~~

**Comment by oehhar** [comment]
Sergey,
thanks for the proposed fix.
Should I prepare a pull request and bring it to th attention of memononen ?

Thank you,
Harald
