### ISSUE TITLE
Regression from commit e7f5981 breaks many hitherto valid SVG icons

### ISSUE THREAD

**Issue by akien-mga** [memononen/nanosvg#188]
We use nanosvg in https://github.com/godotengine/godot, and after syncing with the current `master` branch, most of our SVG icons end up broken ([downstream issue](https://github.com/godotengine/godot/issues/43641)).

- Before (c1f6e20):

![Screenshot_20201118_120142](https://user-images.githubusercontent.com/4701338/99522390-dd9f4280-2995-11eb-872a-237e93aea851.png)

- After (cc6c08d, but bisected regression to e7f5981):

![Screenshot_20201118_115850](https://user-images.githubusercontent.com/4701338/99522024-6e295300-2995-11eb-9957-457a4e0d4f16.png)

I bisected the regression to:
```
e7f5981b1efef8cb5db6f62915ca4e25482b1e5b is the first bad commit
commit e7f5981b1efef8cb5db6f62915ca4e25482b1e5b
Author: Mikko Mononen <memononen@gmail.com>
Date:   Mon Sep 28 10:35:41 2020 +0300

    Fix for #178
    
    - make sure nsvg__addPath() hands only valid number of pointts (1+N*3)
    - require moveTo path command before handling other commands
    - require (sign+)digit for a valid path command coordinate
    - allow to add bezier segment only after there’s at leat one point (now
    also consistent with nsvg__lineTo)

 src/nanosvg.h | 49 +++++++++++++++++++++++++++++++++++++------------
 1 file changed, 37 insertions(+), 12 deletions(-)
```
CC @memononen 

I haven't investigated further yet to see if it's actually most Godot icons which are invalid, or if it's indeed a wrong change in e7f5981b1efef8cb5db6f62915ca4e25482b1e5b.

For the reference, here's the relevant Godot code that uses nanosvg to import SVG files as textures: https://github.com/godotengine/godot/blob/master/modules/svg/image_loader_svg.cpp

**Comment by akien-mga** [comment]
Here's one of those icons which are now broken with e7f5981:
[ToolMove.zip](https://github.com/memononen/nanosvg/files/5559591/ToolMove.zip)

The full icon set is in https://github.com/godotengine/godot/tree/master/editor/icons

I tried this `ToolMove.svg` icon with the example code in https://github.com/memononen/nanosvg/tree/master/example (by replacing `23.svg` and `nano.svg`, here's the output in e7f5981:
![Screenshot_20201118_121424](https://user-images.githubusercontent.com/4701338/99523616-9a45d380-2997-11eb-8195-c5d52c799b40.png)
![Screenshot_20201118_121550](https://user-images.githubusercontent.com/4701338/99523780-cd886280-2997-11eb-8218-24e439664e58.png)
(Second screenshot upscaled by 1600%.)

Here's how it looks like with e7f5981 reverted:
![Screenshot_20201118_121652](https://user-images.githubusercontent.com/4701338/99523872-f27cd580-2997-11eb-9f32-79a2ca87f264.png)
![Screenshot_20201118_121740](https://user-images.githubusercontent.com/4701338/99523955-0f190d80-2998-11eb-9d10-ea7f23f13b8d.png)

(All these icons are MIT licensed, you're welcome to use any of them as regression test material.)

**Comment by fvogelnew1** [comment]
The following patch fixes the regression:

Change line 1477 of nanosvg.h from:
-	return nsvg__isdigit(*s);

To:
+	return (nsvg__isdigit(*s) || *s == '.');
 
Valid floating point numbers may start by a dot.

With this the icon displays as expected.

**Comment by fvogelnew1** [comment]
And of course the comment at the previous line may be updated.

**Comment by fvogelnew1** [comment]
Fix pushed to Tk:  https://core.tcl-lang.org/tk/info/2b07cb2b9e86e2c4

**Comment by oehhar** [comment]
Great work. Also pushed to https://github.com/oehhar/tksvg

Thank you, Francois, that you care so well !

Thanks,
Harald

**Comment by akien-mga** [comment]
@fvogelnew1 Do you want to make a PR to this repo so that @memononen can merge it when they get to it? (And for other downstream users to have a clearly visible PR to cherry-pick in the meantime.)

**Comment by memononen** [comment]
@akien-mga Thanks for debugging it, and @fvogelnew1 thanks for the PR. Merged.
