### ISSUE TITLE
bad svg display

### ISSUE THREAD

**Issue by sezero** [memononen/nanosvg#213]
We noticed this in [SDL_image](https://github.com/libsdl-org/SDL_image) [1]: The following svg logo (as taken from [Wikipedia](https://en.wikipedia.org/wiki/Scalable_Vector_Graphics)): 
![SVG_Logo](https://user-images.githubusercontent.com/4222725/168709039-2eb3c13f-a652-49d3-a22d-f18b019df8e9.svg)

... is badly decoded and displayed: 
![Screenshot-svg](https://user-images.githubusercontent.com/4222725/168709083-55ff0e6e-f2b6-4810-b8b2-95dc0539f3d5.png)

GIMP renders it correctly.

I don't have a patch.

[1] https://github.com/libsdl-org/SDL_image/issues/239

**Comment by jiongt** [comment]
this is nanosvg not support "defs"

**Comment by sezero** [comment]
So it's a missing feature in nanosvg? I hope it gets added.
