### ISSUE TITLE
Closed paths are not positioned correctly?

### ISSUE THREAD

**Issue by FranksMathematics** [memononen/nanosvg#228]
Hi,
i am experiencing a weird bug (or maybe it is just me doing something wrong): All paths, which are closed are moved to the upper left of the image.  It is plotted correctly in Firefox and other.

These closed loops mainly contained letters, or representate letters, you can see some letters in this chaos. All other paths are fine.

Is this an issue with nanosvg or with the underlying svg? (It was automatically generated from svg2pdf and reduced using svgcleaner)

Thanks in advance!
![closed](https://user-images.githubusercontent.com/97291636/191075885-1e3ca8fc-087c-4962-b3ce-b95fe56d90c7.jpg)

svg file:
[test.zip](https://github.com/memononen/nanosvg/files/9601006/test.zip)

**Comment by memononen** [comment]
The test file is some electric diagram for a house, is that correct one?
If yes, then it seems to contain a lot of `<symbol>` tags which are not supported.

**Comment by FranksMathematics** [comment]
Yes, you are correct - it is an electric diagram. 
Alright, if it contains a lot of unsupported symbol-tags (I wasn't aware of this), then I guess I am just unlucky and have to find another way... To bad, this approach using NanoSVG looked very promising and easy to access. Or maybe I do some work and replace all those use-blocks with the associated symbol, if that is possible at all...

Thank you for your help!
