### ISSUE TITLE
bug nsvg__pathArcTo()

### ISSUE THREAD

**Issue by maxlem** [memononen/nanosvg#23]
Hi,

Try the following path and you will get a parse error due to a division by 0 in  nsvg__pathArcTo()
```
<?xml version="1.0" encoding="utf-8"?><svg version="1.1" id="Layer_1" width="10000mm" height="10000mm"><path d="M40.7595, -20.5388 A38.200000000000074,38.200000000000074,0,0,1,32.0609, -22.2933"/></svg>
```
The included patch fixes the bug and does not seem to create regression, as observed by the folowing screen shots
![4cornerbig](https://cloud.githubusercontent.com/assets/10455465/5683324/de541cb6-97f4-11e4-8620-01b716b75cd8.PNG)

![4cornersmall](https://cloud.githubusercontent.com/assets/10455465/5683327/e353cfe0-97f4-11e4-9f39-4656a6b7c0ae.PNG)

patch:
```
Index: trunk/src/nanosvg.h
===================================================================
--- trunk/src/nanosvg.h	(revision 50)
+++ trunk/src/nanosvg.h	(working copy)
@@ -1887,7 +1887,7 @@
 	t[4] = cx; t[5] = cy;
 
 	// Split arc into max 90 degree segments.
-	ndivs = (int)(fabsf(da) / (NSVG_PI*0.5f) + 0.5f);
+	ndivs = (int)(fabsf(da) / (NSVG_PI*0.5f) + 1.0f);
 	hda = (da / (float)ndivs) / 2.0f;
 	kappa = fabsf(4.0f / 3.0f * (1.0f - cosf(hda)) / sinf(hda));
 	if (da < 0.0f)
```

**Comment by memononen** [comment]
What is the shape supposed to be? Chrome refuses the above file, and OSX Preview does not render anything at all. Illustrator shows this (I think it is wrong):
![screen shot 2015-01-09 at 19 42 24](https://cloud.githubusercontent.com/assets/5249992/5684301/b6e53ef6-9837-11e4-9e82-63c6f0449df5.png)

**Comment by maxlem** [comment]
supposed to be an open arc. the shape you attached, but open.

Note that the header I provided may be wrong, in my project I only use the
lib as a path parser, I don't produce actual files.

**Comment by maxlem** [comment]
go to the code, and think to what scenario may lead to ndivs == 0, and thus
INF, and NAN later on. What stuns me is that it will do so for quite large
angles, so the lib would fail on a lot of arcs, The bug appear to big to
have gone unoticed long...

On Fri, Jan 9, 2015 at 1:30 PM, maxime lemonnier <maxime.lemonnier@gmail.com

**Comment by maxlem** [comment]
with this header chrome will render it too:

<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
  "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="20cm" height="20cm" viewBox="-50 -50 500 500"
     xmlns="http://www.w3.org/2000/svg" version="1.1">
<path d="M40.7595, -20.5388
A38.200000000000074,38.200000000000074,0,0,1,32.0609, -22.2933"/>
</svg>

On Fri, Jan 9, 2015 at 1:34 PM, maxime lemonnier <maxime.lemonnier@gmail.com
> wrote:

> go to the code, and think to what scenario may lead to ndivs == 0, and
> thus INF, and NAN later on. What stuns me is that it will do so for quite
> large angles, so the lib would fail on a lot of arcs, The bug appear to big
> to have gone unoticed long...
>
> On Fri, Jan 9, 2015 at 1:30 PM, maxime lemonnier <

**Comment by maxlem** [comment]
I don`t understand with both software insist on closing the path, though,
but I`m no svg expert

On Fri, Jan 9, 2015 at 1:40 PM, maxime lemonnier <maxime.lemonnier@gmail.com
> wrote:

> with this header chrome will render it too:
>
> <?xml version="1.0" standalone="no"?>
> <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
>   "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
> <svg width="20cm" height="20cm" viewBox="-50 -50 500 500"
>      xmlns="http://www.w3.org/2000/svg" version="1.1">
> <path d="M40.7595, -20.5388
> A38.200000000000074,38.200000000000074,0,0,1,32.0609, -22.2933"/>
> </svg>
>
> On Fri, Jan 9, 2015 at 1:34 PM, maxime lemonnier <

**Comment by maxlem** [comment]
I realized my tests were weak, always the same arc angles. I tested by varying arc angle directly, and now I'm pretty much convinced my patch is good, here's two exteme cases:

![4cornerbigarc](https://cloud.githubusercontent.com/assets/10455465/5685305/1705034c-9807-11e4-9e65-43972e110539.PNG)
![4cornersmallarc](https://cloud.githubusercontent.com/assets/10455465/5685308/195f967a-9807-11e4-9406-238a756e1fcf.PNG)

**Comment by maxlem** [comment]
my test case can be reproduced by varying arcRadius and scale in the code below (which represents the <path> section, of course)
'''
        "M arcRadius, 0"
        "L scale - arcRadius, 0"
        "A arcRadius,arcRadius,0,0,1,scale, arcRadius"
        "L scale, scale - arcRadius"
        "A arcRadius,arcRadius,0,1,1,scale - arcRadius, scale"
        "L arcRadius, scale"
        "A arcRadius,arcRadius,0,1,0,0, scale- arcRadius"
        "L 0, arcRadius "
        "A arcRadius,arcRadius,0,1,0,arcRadius, 0"
        "z"
'''

**Comment by memononen** [comment]
Yes, I do see the problem with the code, but it was not clear from the original report what the expected behavior was, as the screenshots were different than the test data.

The reason the shape is closed is that the default path style is black fill, no stroke. Filled paths are always closed.

Your fix looks good, not only to prevent div/0, the there always should be at least two iterations in the loop. Apart from the example files from the SVG spec, I have not found a single file out there that uses arcs.

Thanks, for finding, I'll commit a fix asap.

**Comment by maxlem** [comment]
Yes I did realized that when I tried i ' ndivs :)

Thanks for the svg file explanation, and for your library.
