### ISSUE TITLE
nanosvg doesnt render beautyline icons

### ISSUE THREAD

**Issue by roland-rollo** [memononen/nanosvg#234]
Hi,

Hi I use Arch Linux and standard package for `fuzzel` from official repository doesn't ship with `librsvg` and only `nanosvg`. As result I doesn't see many icons from [beautyline icon set](https://gitlab.com/garuda-linux/themes-and-settings/artwork/beautyline).

Official fuzzel Arch package:
![ps_20221127160141](https://user-images.githubusercontent.com/44477799/204143837-5939e0d3-9b25-4654-bbdb-68abbfdd4314.png)

And fuzzel build from git with `librsvg`:
![ps_20221127160103](https://user-images.githubusercontent.com/44477799/204143847-eef0b158-718c-47bc-98ae-0e602b880551.png)

Is there a chance that `nanosvg` would work with `beautyline`?

**Comment by memononen** [comment]
Can you point me to an icon in the repo that does not work?

**Comment by roland-rollo** [comment]
- https://gitlab.com/garuda-linux/themes-and-settings/artwork/beautyline/-/blob/master/apps/scalable/ark.svg
- https://gitlab.com/garuda-linux/themes-and-settings/artwork/beautyline/-/blob/master/apps/scalable/keepassxc.svg
- https://gitlab.com/garuda-linux/themes-and-settings/artwork/beautyline/-/blob/master/apps/scalable/element.svg
- https://gitlab.com/garuda-linux/themes-and-settings/artwork/beautyline/-/blob/master/apps/scalable/librewolf.svg
- https://gitlab.com/garuda-linux/themes-and-settings/artwork/beautyline/-/blob/master/apps/scalable/theme-config.svg
- https://gitlab.com/garuda-linux/themes-and-settings/artwork/beautyline/-/blob/master/apps/scalable/system-file-manager.svg
- https://gitlab.com/garuda-linux/themes-and-settings/artwork/beautyline/-/blob/master/apps/scalable/gimp.svg
- https://gitlab.com/garuda-linux/themes-and-settings/artwork/beautyline/-/blob/master/apps/scalable/tor.svg

**Comment by wcout** [comment]
These icons have the `<defs>` after the commands, as explained in #202.

**Comment by memononen** [comment]
Looks good, please make a PR.

**Comment by wcout** [comment]
Done in #235

**Comment by memononen** [comment]
Merged.
