### ISSUE TITLE
Unspecified stroke width gets read as 1, causing issues when scaled

### ISSUE THREAD

**Issue by kliment** [memononen/nanosvg#238]
Hello,

While investigating an issue in a project that uses nanosvg, I came across an issue in parsing SVG elements that are not defined. Stroke widths get assigned a default value of 1px, but the SVG specification requires that unspecified values read as 0. This was causing issues for some applications where zero-width strokes are special-cased. It's a one line fix and I verified it works. The fix is to change

https://github.com/memononen/nanosvg/blob/master/src/nanosvg.h#L637

from 1 to 0. Would you like me to submit a PR with the fix?

**Comment by oehhar** [comment]
Dear Kliment,
I think this fix is valuable. A PR would be welcomed.

Thank you and take care,
Harald

**Comment by kliment** [comment]
Done https://github.com/memononen/nanosvg/pull/239

**Comment by oehhar** [comment]
Dear Kliment,
thank you for the action, I appreciate.

May I ask you to be a bit patient, so Mikko (@memononen) may elaborate it.

Take care,
Harald

**Comment by kliment** [comment]
Of course, take as long as you need. We fixed it locally in our project so it's not urgent for me, but I wanted to upstream the fix before I forget.

**Comment by jiongt** [comment]
after set strokeWidth to 0,  this svg can't display:

<svg width="16" height="16" viewBox="0 0 16 16"  xmlns="http://www.w3.org/2000/svg">
<path  stroke="red" d="
  M 7.903,1.638  
  l 2.737,5.650
  z" />
</svg>

**Comment by jiongt** [comment]
path  stroke="red" d=" 
  M 7.903,1.638  
  l 2.737,5.650
  z"

**Comment by kliment** [comment]
Sorry, I have made a mistake - two bits of the specification contradict each other, and I incorrectly interpreted which wins in that case:

https://www.w3.org/TR/SVG/types.html#SVGObjectInitialization - this is fairly clear that unspecified numeric values should be initialized to `zero`

however:

https://www.w3.org/TR/SVG/painting.html#StrokeWidth specifies an initial value of `1` and this supersedes the general rule.

I am retracting this issue and its corresponding MR, and will check whether we can fix the problem we have with scaling of zero-width values by another means. Sorry for the noise.
