### ISSUE TITLE
How to control output size?

### ISSUE THREAD

**Issue by trogmaniac** [memononen/nanosvg#24]
Hi, first of all thanks for the nice library. I spent half a day looking at SVG renderers and yours is the first one that looks easy to use.

My question: When using NSVGrasterizer, how do i control the output size? It seems that whatever parameters i pass as "unit" and "dpi", i always get the size that's given in the SVG, e.g. 900x900 pixels for the famous Ghostscript_Tiger.svg

**Comment by memononen** [comment]
The units in SVG are pretty nasty, especially if you use something else than pixels. When you call `nsvgParseFromFile()` the units and dpi make sure that all shapes and paths are in the same coordinate space, i.e. `nsvgParseFromFile(filename, "px", 96.0f)`returns the paths in pixels and we use 96 DPI to convert points to pixels.

The rasterizer API has very simple transform for view. You pass in width and height in pixels, and then you have scale and offset. That allows you to render the image at different sizes, and also render just a portion of the image. I.e. you may have a sheet of icons, and you can use the offset to render just one of them.

What kind of use case you have in mind?

**Comment by trogmaniac** [comment]
Sorry, i totally overlooked the parameter to the nsvgRasterize() call. Everything is clear now. Thanks.
