### ISSUE TITLE
Filled paths not working?

### ISSUE THREAD

**Issue by th-otto** [memononen/nanosvg#261]
When i replace the image in example1 by the attached one, it only renders the outline:

![Screenshot_20241212_101850](https://github.com/user-attachments/assets/e670a4e9-051e-4b7e-b9fa-54aa9a8d462c)

But it should actually look like

![Screenshot_20241212_102012](https://github.com/user-attachments/assets/9a735949-01e0-47c0-b16b-6283a88cb2ad)

SVG file used:

![23](https://github.com/user-attachments/assets/9e43e543-afa6-4ef8-af9f-7411cca2d9c0)

**Comment by memononen** [comment]
That is what example1 does, it renders the control points of the shapes.

**Comment by th-otto** [comment]
Oops, yes, just realized that, looking closer at the code. Sorry for the noise.
