### ISSUE TITLE
Gradients not rendered

### ISSUE THREAD

**Issue by trogmaniac** [memononen/nanosvg#27]
i found that nsvg__findGradientData is often called with something like "#linearGradient2802" as id, while the stored gradient has an id of "linearGradient2802", so it doesn't get found and therefore not rendered.

I pasted the SVG here: http://pastebin.com/MTA9XNBX

**Comment by memononen** [comment]
The gradients seem to render fine with the recent changes. Should we close the issue?

**Comment by trogmaniac** [comment]
Sorry, i forgot about this one. Yes, the issue is solved.
