### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by aman-bhatia** [memononen/nanosvg#33]
I tried to compile examples. Example2 runs fine but I am getting these errors in example1. Can anyone through some light?

/nanosvg-master/build$ make
==== Building example1 (debug) ====
example1.c
../example/example1.c:141:16: error: unknown type name ‘GLFWwindow’
 void drawframe(GLFWwindow* window)
                ^
../example/example1.c:210:15: error: unknown type name ‘GLFWwindow’
 void resizecb(GLFWwindow* window, int width, int height)
               ^
../example/example1.c: In function ‘main’:
../example/example1.c:220:2: error: unknown type name ‘GLFWwindow’
  GLFWwindow* window;
  ^
../example/example1.c:226:2: warning: implicit declaration of function ‘glfwGetVideoMode’ [-Wimplicit-function-declaration]
  mode = glfwGetVideoMode(glfwGetPrimaryMonitor());
  ^
../example/example1.c:226:2: warning: implicit declaration of function ‘glfwGetPrimaryMonitor’ [-Wimplicit-function-declaration]
../example/example1.c:226:7: warning: assignment makes pointer from integer without a cast [enabled by default]
  mode = glfwGetVideoMode(glfwGetPrimaryMonitor());
       ^
../example/example1.c:227:5: warning: implicit declaration of function ‘glfwCreateWindow’ [-Wimplicit-function-declaration]
     window = glfwCreateWindow(mode->width - 40, mode->height - 80, "Nano SVG", NULL, NULL);
     ^
../example/example1.c:227:35: error: ‘GLFWvidmode’ has no member named ‘width’
     window = glfwCreateWindow(mode->width - 40, mode->height - 80, "Nano SVG", NULL, NULL);
                                   ^
../example/example1.c:227:53: error: ‘GLFWvidmode’ has no member named ‘height’
     window = glfwCreateWindow(mode->width - 40, mode->height - 80, "Nano SVG", NULL, NULL);
                                                     ^
../example/example1.c:235:2: warning: implicit declaration of function ‘glfwSetFramebufferSizeCallback’ [-Wimplicit-function-declaration]
  glfwSetFramebufferSizeCallback(window, resizecb);
  ^
../example/example1.c:235:41: error: ‘resizecb’ undeclared (first use in this function)
  glfwSetFramebufferSizeCallback(window, resizecb);
                                         ^
../example/example1.c:235:41: note: each undeclared identifier is reported only once for each function it appears in
../example/example1.c:236:2: warning: implicit declaration of function ‘glfwMakeContextCurrent’ [-Wimplicit-function-declaration]
  glfwMakeContextCurrent(window);
  ^
../example/example1.c:248:2: warning: implicit declaration of function ‘glfwWindowShouldClose’ [-Wimplicit-function-declaration]
  while (!glfwWindowShouldClose(window))
  ^
../example/example1.c:250:3: warning: implicit declaration of function ‘drawframe’ [-Wimplicit-function-declaration]
   drawframe(window);
   ^
make[1]: *** [obj/Debug/example1/example1.o] Error 1
make: *** [example1] Error 2

**Comment by memononen** [comment]
You will need to install GLFW http://www.glfw.org/ to compile the demos.
