### ISSUE TITLE
Incorrect colors

### ISSUE THREAD

**Issue by jry2** [memononen/nanosvg#37]
Library doesn't render proper colors. For example pure white #FFFFFF is rendered as #FCFCFC, you can check whites on tiger from library description. #000000 is rendered as #010101. Gradients seems to be affected to. Do you have any idea what could be source of this problem?

Edit: Maybe this? (an other >> 8 operations)
			int a = ((int)cover[0] * ca) >> 8; 
vs
			int a = ((int)cover[0] * ca) / 255;

**Comment by chrismile** [comment]
I was able to reproduce this bug.
However, changing " >> 8" to " / 255" won't be a solution. The bitshift of 8 is the same as dividing by 255. The problem is the use of premultiplied alpha: The rasterizer uses integer values to represent these values, thus rounding errors occur and the colors a slightly incorrect. I'll send a pull request which includes switching to floating point values. Please test it and say whether it works for you, too.

**Comment by jry2** [comment]
> The bitshift of 8 is the same as dividing by 255.
No, 0xff >> 8 == 0, while 0xff / 0xff == 1.

Your solution works, but floats are twice slower:

original version:
rasterizing image 1800 x 1800
Time: 187675us
writing Ghostscript_Tiger.png

floats version:
rasterizing image 1800 x 1800
Time: 373503us
writing Ghostscript_Tiger2_200@32.png

**Comment by chrismile** [comment]
Yeah, you're right. " >> 8" equals " / 256". Seems like I had the same trouble with it as the author.
I tested it with integers and it works when it is changed to "/ 255" like you first suggested.

**Comment by memononen** [comment]
Sorry for not chiming in earlier, good catch! I think div by 255 is the right choice. I commented on the PR, it would be nice if you could remove the floating point test from the PR.

If you have time, could you test if these old tricks are any faster than div 255:
```C
inline int nsvg__div255(int x)
{
    return (x + 1 + ((x+1) >> 8)) >> 8;
}
```
or:
```C
inline int nsvg__div255(int x)
{
    return ((x+1) * 257) >> 16;
}
```

Source: http://stackoverflow.com/questions/1102692/how-to-do-alpha-blend-fast

**Comment by jry2** [comment]
Benchmark on Ghostscript_Tiger.svg rendered to 4500x4500px. Visual C++ 2015 RC, Release version.

Original (faulty) code ">> 8":
915ms

Fixed version "/ 255": 
1644ms

Fixed nsvg__div255 v1 "(x + 1 + ((x+1) >> 8)) >> 8": 
1407ms

Fixed nsvg__div255 v2 "((x+1) * 257) >> 16":
1237ms

Fixed nsvg__div255 v2 "((x+1) * 257) >> 16" with nsvg__div255 used also in Premultiply sections:
			// Premultiply
			r = nsvg__div255(cr * a);
			g = nsvg__div255(cg * a);
			b = nsvg__div255(cb * a);
1044ms

Note: output PNG is binary same for all fixed versions. Looks pretty good to me, thank you.
We plan to use your library for real time SVG icon rendering. I want to investigate SSE2 version of  nsvg__scanlineSolid().

**Comment by memononen** [comment]
Excellent! Would you mind making a new clean PR with your latest changes using the v2 method?

SSE definitely helps with the scanline painting. Another option to speed is to try out the rendering algorithm from AGG to see if is any faster. IIRC it is a bit more analytical (i.e. does not do multiple vertical passes) when finding the scanline mask.

**Comment by jry2** [comment]
I will prepare PR.

I did also some cleanup of VS 2015 warnings. Are you interested in another PR?

**Comment by memononen** [comment]
Warnings clean is good as long as it does not barf on other compilers :)

**Comment by jry2** [comment]
I see you was faster with fix, thank you. 
I will open another issue for VC2015 warnings.
