### ISSUE TITLE
Rasterize with background color ?

### ISSUE THREAD

**Issue by cho934** [memononen/nanosvg#54]
Hi, 
I've just tested successfully this library. But the background is always black. 

Is it possible to change it ?

**Comment by memononen** [comment]
The background is set to transparent. Currently there's no way to change that. The background is cleared here:
https://github.com/memononen/nanosvg/blob/master/src/nanosvgrast.h#L1380

**Comment by cho934** [comment]
Thanks for the answer.
Great if it is transparent. I'm using SDL2 and I try to find why I can't see the background behind my svg image. It' completely black. 
For example if I display the svg nano.svg, it displays a black square.

**Comment by memononen** [comment]
The image has premultiplied alpha. You should that sdl treats the image that way too.

**Comment by cho934** [comment]
I don't understand because the function "nsvgRasterize" doesn't have an alpha settings and in the description, it is noticed the following:

// Rasterizes SVG image, returns RGBA image (non-premultiplied alpha)
...
void nsvgRasterize(NSVGrasterizer* r,
				   NSVGimage* image, float tx, float ty, float scale,
				   unsigned char* dst, int w, int h, int stride);

Could you please explain more clearly ?

**Comment by memononen** [comment]
Ah, sorry! The rasterizer is premultiplied alpha, but the result is 'regular' alpha. Could you post the problematic image? Does it look ok in image viewer? Just trying to rule nanosvg vs sdl bug.

**Comment by cho934** [comment]
Finally, I found the solution. I forgot the two first bit in the alpha mask in the function SDL_CreateRGBSurfaceFrom() :(

Here is my working function using SDL2 and nanosvg. Then you can make your rendering as usual using SDL2.
You can use the function SDL_SetTextureAlphaMod() to increase or decrease the transparency of the SDL texture.

Thank you a lot for your time.

```
bool LTexture::loadFromSVG(SDL_Renderer* gRenderer, std::string path)
{
	//using nanosvg
	NSVGimage *image = NULL;
	NSVGrasterizer *rast = NULL;
	unsigned char* img = NULL;

	const char* filename = path.c_str();

	//printf("parsing %s\n", filename);
	image = nsvgParseFromFile(filename, "px", 96.0f);
	if (image == NULL)
	{
		printf("Could not open SVG image.\n");
		goto error;
	}

	//Get image dimensions
	mWidth = (int) image->width;
	mHeight = (int) image->height;

	rast = nsvgCreateRasterizer();
	if (rast == NULL)
	{
		printf("Could not init rasterizer.\n");
		goto error;
	}

	img = (unsigned char*) malloc(mWidth * mHeight * 4);
	if (img == NULL)
	{
		printf("Could not alloc image buffer.\n");
		goto error;
	}

	//printf("rasterizing image %d x %d\n", w, h);
	nsvgRasterize(rast, image, 0, 0, 1, img, mWidth, mHeight, mWidth * 4);

	//write PNG image in a file
	//printf("writing svg.png\n");
	//stbi_write_png("svg.png", mWidth, mHeight, 4, img, mWidthw * 4);

	mImage = SDL_CreateRGBSurfaceFrom(img, //pointer to the pixels
			mWidth, //Width
			mHeight, //Height
			32, //Depth (bits per pixel)
			mWidth * 4, //Pitch (width*depth_in_bytes, in this case)
			0x000000FF, //Red mask
			0x0000FF00, //Green mask
			0x00FF0000, //Blue mask
			0xFF000000); //Alpha mask (no alpha in this format)

	mTexture = SDL_CreateTextureFromSurface(gRenderer, mImage);

	//Return success
	return mTexture != NULL;

error:
	nsvgDeleteRasterizer(rast);
	nsvgDelete(image);
	return 0;
}

void LTexture::setAlpha(Uint8 alpha)
{
	//Modulate texture alpha
	SDL_SetTextureAlphaMod(mTexture, alpha);
}

void LTexture::render(SDL_Renderer* gRenderer, int x, int y, SDL_Rect* clip, double angle,
		SDL_Point* center, SDL_RendererFlip flip)
{
	//Set rendering space and render to screen
	SDL_Rect renderQuad =
	{ x, y, mWidth, mHeight };

	//Set clip rendering dimensions
	if (clip != NULL)
	{
		renderQuad.w = clip->w;
		renderQuad.h = clip->h;
	}

	//Render to screen
	SDL_RenderCopyEx(gRenderer, mTexture, clip, &renderQuad, angle, center, flip);
}
```
