### ISSUE TITLE
nanosvg and OpenCV

### ISSUE THREAD

**Issue by alecive** [memononen/nanosvg#60]
Hello @memononen ,

I discovered this little neat library and I think that is perfect for my `svg` manipulation goals. However, I am having some problems with the rasterization step. 
What I am currently doing is:
 * read an `svg` image
 * rasterize it into a memory buffer
 * read this buffer from OpenCV and create a `cv::Mat` from the buffer
 * display the `cv::Mat`

The source code is available here: https://github.com/ScazLab/snap_circuits/blob/master/snap_circuits_visualization/visualizer.cpp 

This is the result (left: original, right: processed by nanosvg and OpenCV):
![img1](https://cloud.githubusercontent.com/assets/4378663/12795778/a65b9726-ca89-11e5-9921-f92904fe6072.png)

As you can see, there are some issues:

 * [ ] The background of the rasterized image is black. Would it be possible to change it to white? I tried on my own but I was not able to.
 * [ ] The edges are not antialiased as it is clear from the top right part of the rasterized image;
 * [x] The colorspace is wrong between the two libraries. Now, in this regard there are many way one can proceed in order to solve this issue. Unfortunately, OpenCV works with `BGRA` color space (instead of RGBA). I could either create my own conversion method, search for something suitable in the openCV library, or patch your library. I think that the best way would be the latter: I was thinking to a flag to add to `nsvgRasterize` in order to choose the color space. I already did a very dirty modification of your library in order to achieve this, and this is the result:

![img2](https://cloud.githubusercontent.com/assets/4378663/12796044/e7f3ca7c-ca8a-11e5-9b77-6ce38838a4eb.png)

What do you think? My modifications to the library are available here https://github.com/ScazLab/snap_circuits/blob/master/lib/include/nanosvg/nanosvgrast.h , but I think you can have better ideas to do that :)

**Comment by memononen** [comment]
I think the RGBA->BGRA swizzling is better done outside nanosvg, it is very simple function.

I'm not familiar with OpenCV. But it looks like it is not treating alpha at all. If you look at the alpha value at some known pixels, i.e. top-left corner and at center, what do you get back from the OpenCV image data?

Also, if you blit AA image on top of itself many times, the outline will eventually look aliased. Maybe you should clear the screen after each frame?

**Comment by alecive** [comment]
Ok for the RGBA→BGRA (I was only asking if you were interested).

Regarding OpenCV, you're right, it might be possible that it's not processing the alpha channel (or rendering at screen).

Regarding the last sentence: sorry for the ignorance, but what doe it mean _blit the AA image on top of itself many times_?

**Comment by memononen** [comment]
Blitting: if you have color RGBA(255, 0, 0, 32) and blit it over RGBA(0,0,0,255) multiple times, the color will eventually be more and more red. If you have antialised image, and you blit it over itself many times, the edges will eventually become aliased.

It does not look like you are not clearing the screen between frames, so it might have been possible that that is causing the aliasing. Anyways, it looks like image drawing is not dealing with alpha properly.

**Comment by alecive** [comment]
I think that the problem is definitely depending on how OpenCV deals with alpha channels. Apparently, it does deal with them , but the function used to show them into a window does not.
Thank you!

**Comment by TanFluent** [comment]
@alecive hi，i am struggling to convert svg image to opencv mat. can you share you code on how to do this? LOL
