### ISSUE TITLE
missing width + height

### ISSUE THREAD

**Issue by doublex** [memononen/nanosvg#86]
Attached image. Code:
````
NSVGimage *svg = nsvgParseFromFile( "/tmp/no-width-height.svg", "px", 96.0f );
Result: 
svg->width == 0.0 && svg->height == 0.0
````

[no-width-height.zip](https://github.com/memononen/nanosvg/files/974158/no-width-height.zip)

**Comment by lieff** [comment]
Very complex svg, it uses features unsupported by nanosvg.
