### ISSUE TITLE
Issue on computers with some languages

### ISSUE THREAD

**Issue by Meakk** [memononen/nanosvg#90]
The function `atof` use the system locale to define the decimal delimiter character (`.` or `, `).
The side effect is that the decimales are discarded.
For example `atof("4.5");` returns `4.0`when the locale define `,` as the delimiter.

One correction could be : 

    static NSVG_INLINE float nsvg__atof(const char* s)
    {
    	char o[32] ;
    	strcpy(o, setlocale(LC_NUMERIC, NULL)) ;
    
    	setlocale(LC_NUMERIC,"C");
    	float f = atof(s);
    	setlocale(LC_NUMERIC, o);
    	
    	return f;
    }

**Comment by X-Ryl669** [comment]
That's ugly, to say the least. If you have multiple thread, then any of them will get funky (undefined) results when calling printf/sprintf/etc depending on which locale is current at the time of the call.

You could use the [strtof_l](http://www.gnu.org/software/libc/manual/html_node/Parsing-of-Floats.html) function instead so you can skip changing the locale for the whole software and also detect float errors.
strtof_l is available on GNU libc (so it might not be available on Visual Studio for example)

Else, and I think it's better handled this way, is to change the locale outside of the nanosvg library (before calling any of its functions). That's how it's supposed to be used I guess.

**Comment by Meakk** [comment]
Agree about the multi-thread issue.
`strtof_l` is not acceptable since my software is built on windows too.
Changing the locale before any nanosvg call doesn't really fix the multi-thread issue.

Maybe the solution is to code a new locale-independent `atof` ?
For example : https://stackoverflow.com/a/4392789/2609654

**Comment by X-Ryl669** [comment]
Nah, it's not acceptable. Their version don't deal with "1.0e10" like string.
You have [_strtof_l](https://msdn.microsoft.com/fr-fr/library/dn320175.aspx) on Visual Studio (and strtof_l if using mingw, obviously). 
So it's a #define away.

The solution might be:
```
static NSVG_INLINE float nsvg__atof(const char* s)
{
#if defined(_MSC_VER)
    static locale_t locale = _create_locale(LC_NUMERIC, "C");
#elif defined(__APPLE__) || defined(__FreeBSD__) || defined(__ANDROID__)
    static locale_t locale = newlocale(LC_NUMERIC_MASK, "C", (locale_t)0);
#endif
    char * end = NULL;
    float f = 
#if defined(_MSC_VER)
    _strtof_l(s, &end, locale);
#elif defined(__APPLE__) || defined(__FreeBSD__) || defined(__ANDROID__)
    strtof_l(s, &end, locale);
#else
    atof(s);
#endif
    return f;
}
```

**Comment by memononen** [comment]
Meh, silly old locale problem.

I think @X-Ryl669 is on right track. Few things before going into PR:
1) I'm not familiar with using locales on statics like that, will it leak?
2) The above code is really hard to read, each platform implementation is so short that you should fold them inside the define instead.

**Comment by lieff** [comment]
There also relatively small realization for C-only locale:
```
double strtod(const char *s, char **sret)
{
  long double r = 0.0; // result
  int e = 0;           // exponent 
  long double d;       // scale
  int sign  = 1;       // +- 1.0
  int esign = 1;
  int i;
  int flags=0;

  while ((*s == ' ') || (*s == '\t')) s++;

  if (*s == '+') s++;
  else if (*s == '-')
  {
    sign = -1;
    s++;
  }

  while ((*s >= '0') && (*s <= '9'))
  {
    flags |= 1;
    r *= 10.0;
    r += *s - '0';
    s++;
  }

  if (*s == '.')
  {
    d = 0.1L;
    s++;
    while ((*s >= '0') && (*s <= '9'))
    {
      flags |= 2;
      r += d * (*s - '0');
      s++;
      d *= 0.1L;
    }
  }

  if (flags == 0)
  {
    if (sret) *sret = (char *)s;
    return 0;
  }

  if ((*s == 'e') || (*s == 'E'))
  {
    s++;
    if (*s == '+') s++;
    else if (*s == '-')
    {
      s++;
      esign = -1;
    }
    if ((*s < '0') || (*s > '9'))
    {
      if (sret) *sret = (char *)s;
      return r;
    }

    while ((*s >= '0') && (*s <= '9'))
    {
      e *= 10;
      e += *s - '0';
      s++;
    }
  }

  if (esign < 0)
    for (i = 1; i <= e; i++) r *= 0.1L;
  else
    for (i = 1; i <= e; i++) r *= 10.0;

  if (sret) *sret = (char *)s;
  return r * sign;
}

```

**Comment by X-Ryl669** [comment]
I have not thought it would lead to so many reactions...
@memononen Yes it leaks one (and only one in the program lifetime) locale object. It's hard to keep the same function signature yet have a temporary storage without re-creating it every call. If allowed to change the function signature to accept a Parser object, then we could move the locale into this parser and have it cleaned correctly. IMHO, the cleanest solution is to modify the function signature and reuse the libc code. 
@lieff Thanks for this code. Just a remark, multiplying by 0.1 and accumulating is the worst idea when dealing with floating point number. 0.1 is not representable cleanly, and this solution will accumulate errors each step. The libc version compute 3 integers X, Y and Z that match the XXXXX.YYYYYYYYY format (X stores the integral part before the comma, and Y stores the fractional part, Z is the 10^log10 of Y). The last step usually consist in `double result = (double)X + (double)Y/(double)Z` so there is no numerical error.

Pseudo-code:
```
float my_atof(const char *str)
{
    char * end = 0;
    float divisor = 1;
    int64 integral = strtoll(str, &end), fractional = 0, exponent = 1; // integral can have up to 52 bits with double
    if (end == NULL) return (float)integral;
    if (*end == '.') {
        const char * frac = end + 1;
        fractional = strtoll(frac, &end);
        for (; end != NULL && frac != end; frac++) 
            divisor *= 10;
    }
    float result = (float)integral + (float)fractional / divisor;
    if (end != NULL && (*end == 'e' || *end == 'E')) {
       exponent = strtol(end+1, &end);
       float exp = 1.0;
       for (int i = 1; i <= exponent; i++) exp *= 10.0;  // Or simply: exp = pow(10, exponent)
       return exponent > 0 ? result * exp : result / exp;
    } 
    return result;
}
```

**Comment by lieff** [comment]
@X-Ryl669 Yes, this realization clearly better and smaller) I just want show that there not much code for own realization. I think it's more clean solution too.

**Comment by memononen** [comment]
Ok... so this is stupidly hairy issue. Here's excellent article and code for stringtofloat: 
http://krashan.ppa.pl/articles/stringtofloat/

That is more dependency than I'm willing to pull into this codebase, and I don't want external depency. I think the best solution with those limitations is to use `strtof_l` and store the locale into the parser object (to have proper lifetime control), and use #defines to make it work on many platforms.

I'm really tight on time, would some of you be willing to make a PR?

**Comment by Cultrarius** [comment]
Why not look up the current decimal pointer char in [locale.h](https://en.wikibooks.org/wiki/C_Programming/locale.h) and if it is anything other than '.' then replace all dots in the input with it?
That would be a lot easier to test and maintain that either a homegrown parser or using #defines.

**Comment by Meakk** [comment]
@Cultrarius The issue is that afaik, nothing prevent the locale to define multi-char decimal separator or some exotic positive and negative signs.
I think it's more complicated than just replace `.` by `lc.decimal_point`.

**Comment by Cultrarius** [comment]
@Meakk Really? I never heard of that, do you have any example of that happening? (I am genuinely curious!)

I mean the methods allow you to set it to anything you want, but is something as exotic as a multi-char separator really something can should be expected?

**Comment by memononen** [comment]
Converting from SVG number format to some exotic number format is not a robust option. I think the above suggeted `atof_l()` with locale stored in the parser context is the way to go.

**Comment by X-Ryl669** [comment]
Also, there is the issue with the "space" char for thousand ot ten of thousands separator. In Hindi, IIRC, "10 400" is not 10 followed by 400, it's 10400. This is problematic for path parsing, for one.
Anyway, I'll give a shot to a PR. I'm changing the signature to `static NSVG_INLINE float nsvg__atof(const char* s, const NSVGparser * parser)`. Are you ok with this ?

**Comment by memononen** [comment]
@X-Ryl669 yes, that's ok. Please take a look at how the parser object is named elsewhere (it's just `p`) and mimic the coding style otherwise too. Saves us few rounds of PR updates.

**Comment by X-Ryl669** [comment]
Proposing PR#91. Finally, used another strategy that's less intrusive. I'm setting a thread local locale set to "C" (yes, that's possible) in the beginning of the parseImage function, and restoring the previous locale upon leaving the function. Since it's per thread, it does not break the program wide defined locale, and we don't need to change the numerous "atof" calling sites.

I've tested it with french locale (added a `setlocale(LC_NUMERIC, "fr_FR.UTF-8")` in the example2 with the svg file called drawing.svg. Without the patch, the green pill on the bottom right disappear, it doesn't anymore with the change. Please test in your case, and report if the bug is fixed for you.

Cheers!

**Comment by X-Ryl669** [comment]
BTW, if you don't set the locale yourself in the program, it'll be set to "C" by default **whatever the LANG/LC_ALL environment variable**.
Also, please try this code on Windows, I don't have any windows box right now to check it.

**Comment by memononen** [comment]
@Meakk can you test the code from #91 on windows?

**Comment by Meakk** [comment]
Windows (en_US) / MinGW : Build KO (error: 'locale_t' was not declared in this scope)
Windows (en_US) / Visual Studio : Build OK
OSX (fr_FR) / clang : Build KO (error: unknown type name 'locale_t')

**Comment by Meakk** [comment]
Using `xlocale.h` instead `locale.h` on OSX fix the build error (and the initial issue on fr_FR)

**Comment by X-Ryl669** [comment]
Can you try with `xlocale.h` everywhere ? It's strange it does not work with MinGW since it's GCC. Can you try to move the new part to a `#ifdef _WIN32` section instead of `#ifdef _MSC_VER` ?

**Comment by Meakk** [comment]
Changing to `#ifdef _WIN32` : undefined reference to `_configthreadlocale'.
`xlocale.h` is not found by MinGW.

**Comment by Meakk** [comment]
Moreover, it looks that, the per-thread locale function on linux is `uselocale`, not `setlocale`.

**Comment by X-Ryl669** [comment]
Nah, 

There are 2 possibilities. Either mingw use Glibc and you should have the `uselocale` stuff, either it uses msvcrt's libc and you should have the `_configthreadlocale` stuff. IIRC, it's the second case, you must `#include <locale.h>`.

See https://stackoverflow.com/questions/33647271/how-to-use-configthreadlocale-in-mingw

**Comment by Meakk** [comment]
I've spent the last hour trying to figure out a way to build your code on MinGW without success.  
I guess the support is limited when we are using non-standard C code.

**Comment by X-Ryl669** [comment]
Ok. 

Solution 1: Is it possible to detect it's mingw ? and if so, let's `#define NSVG_[...]_LOCALE ` (I mean empty define in that case, since it's not possible to sort this out on this compiler.

Solution 2: Consider this as a non-issue and let the caller of Nanosvg set the locale they want. Said differently: close this bug with no change to the code base, or better put a comment somewhere telling that the locale should be set to "C" when calling nanosvg, and how to do that on posix and win32.

What do you think is best ?

**Comment by Meakk** [comment]
Or solution 3 : Change the locale at parser creation and restore it at deletion. (and specify in the documentation that the parser modifies the locale for numerics during the call, advising the user to protect his code by a mutex if he is planning to display numeric data somewhere in another thread)

**Comment by lieff** [comment]
Or solution 4: use own C only locale atof. Thread independent, do not use TLS, far more portable.

**Comment by X-Ryl669** [comment]
@memononen : What solution do you prefer ?

**Comment by memononen** [comment]
Was there some problem with the `atof_l()` version with mingw? I'd still prefer things to just work. 

If it is no-go, I think I'll prefer 2, and let's make simple set/restore type of function in the example which is simple enough to copy/paste on most platforms.

**Comment by memononen** [comment]
@X-Ryl669 I gave this one more thought over night and looked at other libraries. Quite a few libraries just use `strtod` (i.e. Skia) directly or have rolled their own string to float (quite a few json libs).

While I would like the solution to be as correct as possible, I think making something portable and practical is more important.

For that reason, I think rolling our own `atof()` is a better solution than spending time on trying to get the locale quirks right. The most complicated string-to-float implementations take care of things like float->string->float round trips, but I think in our case the bar should be visual quality. So something along the lines of your earlier pseudo code would be acceptable.

**Comment by Meakk** [comment]
I looked at @X-Ryl669 code, and tried it a little bit.
I think his approach using `strtol` is the good one, but it fails on `+.5e-2`.

Here is the SVG spec for numbers : 
`number ::= integer ([Ee] integer)? | [+-]? [0-9]* "." [0-9]+ ([Ee] integer)?`  

Here is my correction (with some tests) : http://ideone.com/1ClEen

**Comment by X-Ryl669** [comment]
Thanks Meakk. I've simplified a bit, and fixed a bug that accepted 34f4:
```
float my_atof(const char *str)
{
    char * end = str;
  
    float res = (float)strtoll(end, &end, 10);
	float sign = res < 0 ? -1 : 1;
    
    if (*end == '.')
    {
    	char* beg = end+1;
    	long long frac = strtoll(beg, &end, 10);
    	res += sign * frac/pow(10, end-beg);
    }
    
    if (*end == 'e' || *end == 'E') res *= pow(10, strtol(end+1, &end, 10));
    
    return res;
}
```

Here it is: http://ideone.com/NVJN2W

**Comment by X-Ryl669** [comment]
BTW, since there is already code that tries to compute the number of char in a number (`nsvg__parseNumber`), and we are also computing this here, I wonder if we returned `end` in the atof function would be enough to compute both at the same time, and reduce the code base size.

**Comment by Meakk** [comment]
`34f4` is not a valid number according the SVG spec but yes, check for the exponential character is more robust.

**Comment by X-Ryl669** [comment]
If we merge `nvg_parseNumber` and `nvg_atof`, this gives this:
```
float my_atof(const char *str, char ** last)
{
    char * end = (char*)str;
  
    float res = (float)strtoll(str, &end, 10);
	int badConv = end == str;
    float sign = res < 0 || (*end == '-' && ++end) ? -1 : (*end == '+' && ++end) || 1; // Trim sign 
	
	if (badConv && *end != '.') // Invalid input
	{
		if (last != NULL) *last = (char*)str;
		return 0;
	}
	

    if (*end == '.')
    {
    	char* beg = ++end, *tmp = 0;   // So end is correct when returning below
    	long long frac = strtoll(beg, &tmp, 10);
        if (*beg < '0' || *beg > '9') 
        {
        	if (last != NULL) *last = end;
        	return res;
        }
        end = tmp;
    	res += sign * frac/pow(10, end-beg);
    }
    
    if (*end == 'e' || *end == 'E') res *= pow(10, strtol(end+1, &end, 10));
	
	if (last != NULL) *last = end;
    return res;
}
```

**Comment by memononen** [comment]
Thanks for the contributions so far, I think we have a little bit to go still :)

`nvg_parseNumber` needs to be able to handle the funkiness of the path commands, i.e. `M1.2-3` is valid. So a combined `nvg_parseNumber` should return `1.2` and have pointer advanced to `3` in that case.

Handling of the sign in @X-Ryl669 's code is too complicated, why not just check for + and -, set sign, and advance the pointer, apply sign after fractional? I don't quite understand the reason for `badConv` checks.

Here's version which has the parseNumber logic in it:
```C
float my_atof(const char *s, char ** last)
{
	const char* first = NULL;
	double res = 0.0, sign = 1;
	
	// Parse sign
	if (*s == '-' || *s == '+') {
		sign = *s == '-' ? -1 : 1;
		s++;
	}
	// Parse integer part
	first = s;
	while (*s && nsvg__isdigit(*s)) {
		s++;
	}
	res = (double)atoi(first);	

	// Parse fractional part	
	if (*s == '.') {
		// skip decimal point
		s++;
		// fraction part
		first = s;
		while (*s && nsvg__isdigit(*s)) {
			s++;
		}
		if (first != s)
			res += (double)atoi(first) / pow(10, (int)(s - first));
	}
	
	// Apply sign
	res *= sign;
	
	// Parse exponent
	if (*s == 'e' || *s == 'E') {
		double esign = 1;
		const char* r = s;
		// skip E
		s++;
		// parse exponent sign
		if (*s == '-' || *s == '+') {
			esign = *s == '-' ? -1 : 1;
			s++;
		}
		// Parse exponent
		first = s;
		while (*s && nsvg__isdigit(*s))
			s++;
			
		if (first != s)
			res *= pow(10, esign * (double)atoi(first));
		else
			s = r; // Do not advance the exponent unless we can fully parse it
	}
	
	if (last != NULL) {
		*last = (char*)s;
	}
		
	return (float)res;
}
```

**Comment by X-Ryl669** [comment]
The main point of using `strtoll` / `strtol` is to have the number of char consumed as output (and if it was possible to convert the integer part. 
The goal of `badConv` is to avoid *advancing* the pointer when it fails decoding. 
And you can only know it fails after you've eaten the sign and the dot (so after you've eaten them). 

Trimming the sign in my code is funky, I agree. I'm sorry, I'm a C++ developer and having to declare variable on top is a PITA for me. Hopefully, it's the last line, so it can be expanded to
```
float sign = ret < 0 ? -1 : 1;
if (*end == '-') { sign = -1; end++; }
if (*end == '+' && end == str}  end++;  // Avoid  accepting +34.+4
```

The difference between my last 2 codes here is just to handle the errors correctly. Your code will fail, for example, at `-.e` or `+3.3e`as it will eat everything (yet, it's not a valid number) 

Try your code on the ideone I've posted, I've some (hard) test cases.

**Comment by memononen** [comment]
Good points. PITA is such a PITA excuse to make things more complicated ;)

Let's make advancing super obvious then.
The grammar is specified here: https://www.w3.org/TR/SVG/paths.html#PathDataBNF
It says:
```
The processing of the BNF must consume as much of a given BNF production as possible, stopping at the point when a character is encountered which no longer satisfies the production.
```
So as per their example `M 100-200` will become (100, 200), and  `M 0.6.5` will became (0.6, 0.5).

How about this version?
```C
int is_digit(char c)
{
	return c >= '0' && c <= '9';
}

float my_atof(const char *str, char** next)
{
	char* cur = (char*)str;
	char* end = NULL;
	double res = 0.0, sign = 1.0;
	long long intPart = 0, fracPart = 0;
	char hasIntPart = 0, hasFracPart = 0;

	if (next != NULL) *next = cur;

	// Parse optional sign
	if (*cur == '+') {
		cur++;
	} else if (*cur == '-') {
		sign = -1;
		cur++;
	}

	// Parse integer part
	if (is_digit(*cur)) {
		// Parse digit sequence
		intPart = (double)strtoll(cur, &end, 10);
		if (cur != end) {
			res = (double)intPart;
			hasIntPart = 1;
			cur = end;
			// Consume input up to this point (i.e. 123)
			if (next != NULL) *next = cur;
		}
	}

	// Parse fractional part.
	if (*cur == '.') {
		cur++; // Skip '.'
		if (hasIntPart) {
				// Consume input up to this point (i.e. 123.)
				if (next != NULL) *next = cur;
		}
		
		if (is_digit(*cur)) {
			// Parse digit sequence
			fracPart = strtoll(cur, &end, 10);
			if (cur != end) {
				res += (double)fracPart / pow(10, (double)(end - cur)) * sign;
				hasFracPart = 1;
				cur = end;
				// Consume input up to this point (i.e. 123.456 or .456)
				if (next != NULL) *next = cur;
			}
		}
	}

	// A valid number should have integer or fractional part.
	if (!hasIntPart && !hasFracPart)
		return 0.0f;

	// Parse optional exponent
	if (*cur == 'e' || *cur == 'E') {
		int expPart = 0;
		cur++; // skip 'E'
		expPart = strtol(cur, &end, 10); // Parse digit sequence with sign
		if (cur != end) {
			res *= pow(10.0, (double)expPart);
			// Consume input up to this point (i.e. 123e-2)
			if (next != NULL) *next = cur;
		}
	}

	return res;
}
```

**Comment by X-Ryl669** [comment]
Almost right ;-).
The line `res = (double)intPart;` should read `res = (double)intPart * sign;` else the negative numbers are not converted correctly.

It seems very verbose and not optimal (since strtoll already parse the sign by itself), but I guess it's easier to read this way.

I've made an ideone from your code (fixed) with my tests:  http://ideone.com/tBNeTA

**Comment by memononen** [comment]
I made it intentionally verbose so that the parsing state machine is visible. I had had time following your code (i.e. badConv actually indicates missing integer part, not a bad conversion per se :)).

Can I ask you to turn this into a PR? I'm currently on a machine that does not have a dev environment set up.

**Comment by X-Ryl669** [comment]
Ok, so let's agree first on what the PR contains. I'm replacing `nsvg__parsenumber` by your `my_atof` renamed as `nsvg__convertNumber` and change all call site to use this. Right ?

**Comment by memononen** [comment]
@X-Ryl669 That was my intent. But, I checked more closely how it's used, and the logic in that damned `nsvg__getNextPathItem` worries me :(. Whilst quite trivial to change, it had some subtle aspects when I made it, I would not like to change too much of code that has been working fine.

So... let's just change `atof()`. Sorry for scrambling around, it's been a while since I touched the code, and I have very little time to concentrate on this at the moment.

**Comment by Meakk** [comment]
Hey guys, any update ?
I can do the PR if you are too busy.

**Comment by memononen** [comment]
I commited a fix. Can you please test it? It worked with the svg files I had in my test folder.

**Comment by Meakk** [comment]
This SVG  fails (and a lot of others from my test base) on both OSX (fr_FR) and Win10 (en_US)

    <?xml version="1.0" encoding="utf-8"?>
    
    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
    	 width="56.693px" height="56.693px" viewBox="0 0 56.693 56.693" style="enable-background:new 0 0 56.693 56.693;"
    	 xml:space="preserve">
    <path d="M54.082,15.5495c-1.8115,0.8047-3.7597,1.3477-5.8051,1.5913c2.0874-1.25,3.6894-3.2305,4.4443-5.5918
    	c-1.9531,1.1587-4.1152,2-6.418,2.4536c-1.8432-1.9643-4.4702-3.1919-7.3769-3.1919c-5.5816,0-10.1069,4.5254-10.1069,10.107
    	c0,0.792,0.0893,1.563,0.2617,2.3027c-8.3999-0.4209-15.8477-4.4443-20.8325-10.5596c-0.8697,1.4922-1.3682,3.2281-1.3682,5.0811
    	c0,3.5063,1.7842,6.5996,4.4961,8.4126c-1.6563-0.0532-3.2154-0.5073-4.5777-1.2647c-0.0009,0.042-0.0009,0.0845-0.0009,0.128
    	c0,4.896,3.4839,8.9809,8.1079,9.9101c-0.8482,0.2305-1.7412,0.3545-2.6631,0.3545c-0.6519,0-1.2847-0.063-1.9019-0.1816
    	c1.2867,4.0151,5.0191,6.9375,9.441,7.019c-3.459,2.711-7.8165,4.3267-12.5523,4.3267c-0.8154,0-1.6196-0.0484-2.4106-0.1411
    	c4.4736,2.8681,9.7856,4.541,15.4931,4.541c18.5908,0,28.7559-15.4009,28.7559-28.7569c0-0.4375-0.0088-0.8745-0.0283-1.3076
    	C51.0137,19.3571,52.728,17.5769,54.082,15.5495z"/>
    </svg>

**Comment by Meakk** [comment]
Remove the sign multiplication on fractional part, it fixes the issue (line 1113)

**Comment by memononen** [comment]
Thanks for finding the bug, pushed fix.
